### PR TITLE
Add the "tinker panic 0" directive to the configuration/template.

### PR DESCRIPTION
**Pull request by kwilczynski**
See the following for details:

  http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1006427

Signed-off-by: Krzysztof Wilczynski <krzysztof.wilczynski@linux.com>

### CODE REVIEW

**Comment by munhitsu** [comment]
please extend changelog and I'm happy to merge

**Comment by kwilczynski** [comment]
Thank you @munhitsu, will do.

**Comment by ashb** [comment]
> The configuration directive tinker panic 0 instructs NTP to not give up if it sees a large jump in time. This is important for coping with large time drifts and also resuming virtual machines from their suspended state.

Do we need to worry that this will could actually mess things up? I forget what brakes if if you reset the clock, particularly in the case where the system clock is fast and we end up resetting the clock back and having times 'repeat'?

**Comment by munhitsu** [comment]
Tiebreaker

Based on evidence supplied and dicsussion with @kwilczynski it's safe to merge.
Additional materials:
http://www.ntp.org/ntpfaq/NTP-s-algo.htm#Q-ALGO-BASIC-STEP-SLEW

@kwilczynski please add issue that formula should detect if we run on baremetal and then disable this option. Low priority as we are all flying in the clouds.

Merging

**Pull request merged**
